### ISSUE TITLE
Lecture 10 checklist

### ISSUE THREAD

**Issue by Kiopp** [Kiopp/Dungeon-Crawler-Game#101]
- [x] Carry on with your implementation adding more features to your project: use issues and PRs to track your work; add unit tests when appropriate.
- [x] List the issues and PRs you worked on during the week in this issue.
- [x] Define a few project goals for the upcoming weeks, create them as issues, list them in this issue.
- [x] Make a new release following Semantic Versioning rules.

**Comment by Kiopp** [comment]
During this week I have worked on #97 #21 and #15

**Comment by Kiopp** [comment]
One of our project goals we have for the coming weeks is to make the first level of the game: #106

**Comment by Vencilo** [comment]
This week I have worked on #131, #126, #120, #112, #116 and #111.

The goal for this week is to have a complete game and to have completed most of the workshops so we do not have a lot of work that needs to be done the last week. Next week the goal is to be done with the game and all the workshops and have prepared for our presentation.

**Comment by majo22wx** [comment]
This week I have worked on #47, #122 and #28.

**Comment by CarlNord01** [comment]
I have worked on #127, #123

**Comment by mowaab** [comment]
This week i have worked on #68, #67, #9
