### ISSUE TITLE
Lecture 11 checklist

### ISSUE THREAD

**Issue by Kiopp** [Kiopp/Dungeon-Crawler-Game#102]
- [x] each student has created at least two to five unit tests with matching PRs and code review
- [x] project has at least one of the following types of tests: Integration tests, Nonfunctional tests (e.g.: performance, capacity), [Optional] Property tests
- [x] code coverage of tests is increased by at least 20%.  List the "starting" and "ending" commits in the "Lecture 11 checklist" issue with the achieved percentage increase.

**Comment by Kiopp** [comment]
Starting commit: [09269c2](https://github.com/Kiopp/Dungeon-Crawler-Game/commit/09269c2f1edb4c4846a2638451977a5747facb10) 
Line coverage: 45% (218 of 483)
Method coerage: 32.6% (32 of 98)

Ending commit: [8f095d3](https://github.com/Kiopp/Dungeon-Crawler-Game/commit/8f095d350b8d32d3920866b55e71c894c2731fe2)
Line coverage: 72.1% (873 of 1210)
Method coverage: 67.8% (177 of 261)

**Comment by Vencilo** [comment]
The BattleManager test can be considered an integration test since it verifies the interactions between the BattleManager and the IBattleEntity (Player/Enemy) components. It test how the BattleManager interacts with mock implementations of the Player and Enemy (mockPlayer, mockEnemy). By using these mocks, the test simulate interactions between the BattleManager, Player and Enemy. It also tests the battle loop, ensuring it correctly handles interactions between the BattleManager, Player and Enemy classes during a battle.

**Comment by mtaromi** [comment]
@Kiopp, @majo22wx, @Vencilo, @mowaab, and @CarlNord01 

Please, mention the unit tests with matching PRs and code review in the comment (each one in a separate comment).

Due Data: **Thursday May 30.**

**Comment by Vencilo** [comment]
#111 Battle manager test. Integration test.

**Comment by Vencilo** [comment]
#116 Entity unit test.

**Comment by Kiopp** [comment]
#78 #79 GameInput unit test

**Comment by Kiopp** [comment]
#173 #167 FaceCamera unit test

**Comment by Kiopp** [comment]
#172 #168 ItemDrop unit tests

**Comment by CarlNord01** [comment]
#175 unit test

**Comment by majo22wx** [comment]
#176 unit tests UIManager

**Comment by mowaab** [comment]
#177 #180 Item unit test

**Comment by mowaab** [comment]
#178 #179 Weapon unit test
