### ISSUE TITLE
Workshop 2 tasks

### ISSUE THREAD

**Issue by majo22wx** [Kiopp/Dungeon-Crawler-Game#25]
### Part 1

- [x] Carry on with your implementation adding more features to your project: use issues to track your work.

- [x] #89 

### Part 2

- [x] Add a .gitignore file to your project
- [x] Has a revert commit (don’t edit history: create a new revert commit!).
- [x] Has a branch implementing a small feature.
- [x] Has a merge commit (of the branch)
- [x] Has a branch in conflict with main/master 
- [x] Try to merge and resolve the merge conflict
- [x] Has working compilation and running instructions in the README.
- [x] Has issues associated with each of your changes.
